name: Main

on:
  push:
    branches:
      - main

jobs:
  docker-push:
      permissions:
        contents: read
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - name: Build
          run: >
            docker build -t onsdigital/eq-runner-mock-cir:latest .
        - name: Push to Docker Hub
          run: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            echo "Pushing with tag [latest]"
            docker push onsdigital/eq-runner-mock-cir:latest
