name: PR

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: '${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  lint-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version-file: '.python-version'

      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs

      - name: Install dependencies
        run: poetry install

      - name: Lint
        run: make lint

      - name: Load schemas
        run: make load-schemas

      - name: Run pytest
        run: make test
